environment: qa
db:
  name: wordpress-qa
  user: root
  pass: qa-example
mysql:
  image: "mysql:5.7.21"
  port: 3306
wordpress:
  replicas: 1
  requests:
    cpu: 100m
    memory: 128Mi
  image: "wordpress:4.9.2-apache"
  port: 80
  hpa:
    min: 1
    max: 3
    target: 50
