apiVersion: v1
kind: Service
metadata:
  name: wordpress-single
  namespace: up-k8s-example-two
spec:
  ports:
  - port: 80
    protocol: TCP
    name: http
  type: LoadBalancer
  selector:
    app: wordpress-single
