apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wordpress-multi
  namespace: up-k8s-example-three
spec:
  template:
    metadata:
      labels:
        app: wordpress-multi
    spec:
      containers:
      - name: wordpress
        image: wordpress:4.9.2-apache
        env:
        - name: WORDPRESS_DB_HOST
          value: "wordpress-multi-mysql-service"
        - name: WORDPRESS_DB_USER
          valueFrom:
            configMapKeyRef:
              name: wordpress-multi-config
              key: db_user
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: wordpress-multi-config
              key: db_password
        ports:
        - containerPort: 80
