apiVersion: v1
kind: Service
metadata:
  name: wordpress-{{ .Values.environment }}-mysql
spec:
  ports:
  - port: {{ .Values.mysql.port }}
  selector:
    app: wordpress-{{ .Values.environment }}-mysql
