apiVersion: v1
kind: Service
metadata:
  name: wordpress-{{ .Values.environment }}
spec:
  ports:
  - port: {{ .Values.wordpress.port }}
    protocol: TCP
    name: http
  type: LoadBalancer
  selector:
    app: wordpress-{{ .Values.environment }}
