apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-intro
spec:
  template:
    metadata:
      labels:
        app: nginx-intro
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
