apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wordpress-multi-hpa-mysql
  namespace: up-k8s-example-four
spec:
  template:
    metadata:
      labels:
        app: wordpress-multi-hpa-mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.7.21
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: wordpress-multi-hpa-config
              key: db_password
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: wordpress-multi-hpa-config
              key: db_name
        ports:
        - containerPort: 3306
