apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: wordpress-hpa
  namespace: up-k8s-example-four
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: wordpress-multi-hpa
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 40
